sb_logger_util2 added
project-sunbird/sunbird-js-utils pull request #16
Opened 2019-02-06 11:46 UTC by yravinderkumar33

2019-02-06 14:54 UTC, anoophm commented on sb_logger_util2/index.js
> +        path: '../logs',
extension is missing

2019-02-06 14:55 UTC, anoophm commented on sb_logger_util2/index.js
> +let loggerInit = false;
change to loggerInitialized

2019-02-06 14:56 UTC, anoophm commented on sb_logger_util2/index.js
> +const init = (newConfig) => {
change to appConfig

2019-02-06 14:57 UTC, anoophm commented on sb_logger_util2/index.js
> +            path: request.route.path,
just request.path

2019-02-06 14:58 UTC, anoophm commented on sb_logger_util2/package.json
> +  "name": "sb_logger_util2",
sb_logger_util_v2

2019-02-09 05:55 UTC, anoophm commented on sb_logger_util_v2/index.js
> +            path: request.path,
we only need id remove rest

2019-02-14 05:42 UTC, HarishGangula requested changes

2019-02-14 05:42 UTC, harishgilimi commented on sb_logger_util_v2/index.js
> +var mkdirp = require('mkdirp');
const

2019-02-14 06:04 UTC, HarishGangula approved these changes

2019-02-14 06:04 UTC, merged